name: Generate ID Tags

on:
  workflow_dispatch:

jobs:
  generate-tags:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        working-directory: ./Character Tags Crawler
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Makefile
        working-directory: ./Character Tags Crawler
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MOEGIRL_COOKIES: ${{ secrets.MOEGIRL_COOKIES }}
        run: |
          make anime_character_guessr
      
      - name: Upload id_tags.json
        uses: actions/upload-artifact@v4
        with:
          name: id-tags
          path: Outputs/id_tags.json
      
      - name: Commit and push id_tags.json
        run: |
          git config --local user.email "${{ github.repository_owner }}@users.noreply.github.com"
          git config --local user.name "${{ github.repository_owner }}"
          git add Outputs/id_tags.json
          git diff --staged --quiet || git commit -m "CI：更新 id_tags.json"
          git push
